### ISSUE TITLE
Landsats missing 5 last characters

### ISSUE THREAD

**Issue by vick25** [sat-utils/sat-search#83] opened 2019-08-22 12:20 UTC
Hello!
The attached picture is showing that some landsats are missing the LGN00 in the output. Might be some parsing issues.

![satsearch_summary](https://user-images.githubusercontent.com/8378428/63513767-fee95880-c4de-11e9-987e-c6b5d2f01328.png)

Regards

**Comment by matthewhanson** [comment] 2019-08-23 17:01
Hi @vick25, we moved to the shortened `id`, so it was intended, but the historical archive mustn't have been updated (I can't remember, it's been a while).

The reason for the shortened id is because the last 5 digits are the ground station and the revision, but we only wanted to have the latest version of a particular record, not multiple versions of the same record, so I removed the ground station identifier and revision so that a newer version would overwrite the old one.

In the next month or two I'll be recreating the Landsat catalog for STAC 0.8.0, so all the ids will be the short version.  I will index that at the API running at https://earth-search.aws.element84.com/stac so that will be up to date.  You can switch to that from the default by setting the SATUTILS_API_URL environment variable to `https://earth-search.aws.element84.com/stac`

I'm closing this, if you come across further issues with the actual Landsat metadata records, or want to discuss this further, open up an issue in https://github.com/sat-utils/sat-stac-landsat

**Closed by matthewhanson** 2019-08-23 17:01 UTC
