### ISSUE TITLE
NASA CMR STAC endpoint usage

### ISSUE THREAD

**Issue by scottyhq** [sat-utils/sat-search#106] opened 2020-10-06 23:03 UTC
https://github.com/nasa/cmr-stac exposes STAC API urls for each NASA distributed archive center (DAAC). This code recently worked to do a search with v0.3.0:

```python
URL = 'https://cmr.earthdata.nasa.gov/cmr-stac/ASF'
results = satsearch.Search.search(url=URL,
                                  collections=['C1595422627-ASF']
                                  )
items = results.items()
print('%s items' % len(items))
```

But now returns everything rather than filtering based on collection, bbox, dates, etc:
`There are more items found (18873861) than the limit (10000) provided.`

Changing the URL to `https://cmr.earthdata.nasa.gov/cmr-stac/ASF/search` results in:

```pytb
SatSearchError: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /cmr-stac/ASF/search/search</pre>
</body>
</html>
```  

Seems this is a server-side issue, but wanted to post an issue here in case there is a workaround with modifying sat-search code.

**Comment by scottyhq** [comment] 2020-11-17 01:11
Just wanted to document that the first error described has been fixed on the https://github.com/nasa/cmr-stac endpoint, but there are still some compatibility issues. Note the endpoint URL has changed slightly:

1) `satsearch` will currently only return the first 500 items even if more are found:
```python
import satsearch
URL='https://cmr.earthdata.nasa.gov/stac/NSIDC_ECS'
results = satsearch.Search.search(url=URL,
                                  collections=['C1908075185-NSIDC_ECS'],
                                  bbox=[-75, 60, -14, 83], # (min lon, min lat, max lon, max lat)
                                  #datetime='2019-07-01/2020-08-15',
                                  #limit=1000,
                                 )
items = results.items()
print('%s items' % len(items))
500 items
```

2) Increasing the `limit` keyword leads to a traceback (`limit=1000`)
```pytb
---------------------------------------------------------------------------
SatSearchError                            Traceback (most recent call last)
<ipython-input-16-25bba36d01ed> in <module>
      5                                   limit=1000,
      6                                  )
----> 7 items = results.items()
      8 print('%s items' % len(items))

~/miniconda3/envs/intake-stac-gui/lib/python3.7/site-packages/satsearch/search.py in items(self, limit, page_limit, headers)
     88     def items(self, limit=10000, page_limit=500, headers=None):
     89         """ Return all of the Items and Collections for this search """
---> 90         found = self.found(headers=headers)
     91         limit = self.limit or limit
     92         if found > limit:

~/miniconda3/envs/intake-stac-gui/lib/python3.7/site-packages/satsearch/search.py in found(self, headers)
     60         url = urljoin(self.url, 'search')
     61 
---> 62         results = self.query(url=url, headers=headers, **kwargs)
     63         # TODO - check for status_code
     64         logger.debug(f"Found: {json.dumps(results)}")

~/miniconda3/envs/intake-stac-gui/lib/python3.7/site-packages/satsearch/search.py in query(self, url, headers, **kwargs)
     78         # API error
     79         if response.status_code != 200:
---> 80             raise SatSearchError(response.text)
     81         return response.json()
     82 

SatSearchError: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
```


3) If 'collections' is not specified we get the same traceback above. for example:
```python
import satsearch
URL='https://cmr.earthdata.nasa.gov/stac/NSIDC_ECS'
results = satsearch.Search.search(url=URL,
                                  #collections=['C1908075185-NSIDC_ECS', 'C1631076758-NSIDC_ECS'],
                                  bbox=[-54, 67.65, -50, 69.37],
                                  datetime='2020-08-15/2020-08-15',
                                 )
items = results.items()
print('%s items' % len(items))
```
An equivalent search directly with the NSIDC API returns 115 datasets (https://nsidc.org/data/search/#startDate=2020-08-15/endDate=2020-08-15/sortKeys=score,,desc/facetFilters=%257B%257D/pageNumber=1/osGeoBbox=N:69.37,S:67.65,E:-50.0,W:-54.0/itemsPerPage=25)

**Comment by matthewhanson** [comment] 2021-01-25 04:34
I believe that all these issues have been resolved in cmr-stac now, but some of the changes may not have made it yet to production.  Will leave it open until it's confirmed.

**Comment by scottyhq** [comment] 2021-02-11 02:04
@matthewhanson things were working as expected last week, but once again I'm encountering errors, for example:
```python
results = satsearch.Search.search(url=URL,
                                  collections=['C1908075185-NSIDC_ECS'],
                                  bbox=[-75, 60, -14, 83], # (min lon, min lat, max lon, max lat)
                                  #datetime='2019-07-01/2020-08-15',
                                  #limit=1000,
                                 )
items = results.items()
print('%s items' % len(items))
```

```pytb
---------------------------------------------------------------------------
SatSearchError                            Traceback (most recent call last)
<ipython-input-10-cb95631244b6> in <module>
      8                                   #limit=1000,
      9                                  )
---> 10 items = results.items()
     11 print('%s items' % len(items))

/srv/conda/envs/notebook/lib/python3.8/site-packages/satsearch/search.py in items(self, limit, page_limit, headers)
     88     def items(self, limit=10000, page_limit=500, headers=None):
     89         """ Return all of the Items and Collections for this search """
---> 90         found = self.found(headers=headers)
     91         limit = self.limit or limit
     92         if found > limit:

/srv/conda/envs/notebook/lib/python3.8/site-packages/satsearch/search.py in found(self, headers)
     60         url = urljoin(self.url, 'search')
     61 
---> 62         results = self.query(url=url, headers=headers, **kwargs)
     63         # TODO - check for status_code
     64         logger.debug(f"Found: {json.dumps(results)}")

/srv/conda/envs/notebook/lib/python3.8/site-packages/satsearch/search.py in query(self, url, headers, **kwargs)
     78         # API error
     79         if response.status_code != 200:
---> 80             raise SatSearchError(response.text)
     81         return response.json()
     82 

SatSearchError: "Request failed with status code 400"
```

**Comment by matthewhanson** [comment] 2021-02-11 06:43
@scottyhq thanks for this, there was a new deployment today and I was able to replicate the problem with sat-search, although a GET request in the browser seems to work:
https://cmr.earthdata.nasa.gov/stac/NSIDC_ECS/search?collections[]=C1908075185-NSIDC_ECS&bbox=-75,60,-58,65

Not sure if bbox is working properly though, as it seems to not have an effect on the number matched from the collection alone.

Will try and replicate this running cmr-stac locally to see if I can get to the bottom of it.

**Comment by matthewhanson** [comment] 2021-02-11 06:57
Interesting, my link above results in a 400 error when  you click on it because it escapes the `[]` into `%5B%5D`.  
But if you then edit the URL in the browser back to [] it gives you a proper response.

**Comment by kearney-sp** [comment] 2021-02-15 20:31
I am having the same issue (see below) with the following search (which worked fine ~2 weeks ago):

`from satsearch import Search


def get_STAC_items(url, collection, dates, bbox):
    results = Search.search(url=url,
                        collections=[collection], 
                        datetime=dates,
                        bounding_box=bbox,    
                        sortby=['-properties.datetime'])

    items = results.items()
    print(f'Found {len(items)} Items')
    return intake.open_stac_item_collection(items)

url = 'https://cmr.earthdata.nasa.gov/stac/LPCLOUD' 
collection = 'C1711924822-LPCLOUD' #HLS
bbox=[-104.79107047,   40.78311181, -104.67687336,   40.87008987]
dates = '2020-01-01/2021-01-10'

cat = get_STAC_items(url,collection,dates,','.join(map(str, bbox)))
`
Which now returns the following error:

`---------------------------------------------------------------------------
SatSearchError                            Traceback (most recent call last)
<ipython-input-7-9f73841e84c7> in <module>
      4 dates = '2020-01-01/2021-01-10'
      5 
----> 6 cat = get_STAC_items(url,collection,dates,','.join(map(str, bbox)))

<ipython-input-6-aed9a4e427b7> in get_STAC_items(url, collection, dates, bbox)
      6                         sortby=['-properties.datetime'])
      7 
----> 8     items = results.items()
      9     print(f'Found {len(items)} Items')
     10     return intake.open_stac_item_collection(items)

/srv/conda/envs/notebook/lib/python3.7/site-packages/satsearch/search.py in items(self, limit, page_limit, headers)
     88     def items(self, limit=10000, page_limit=500, headers=None):
     89         """ Return all of the Items and Collections for this search """
---> 90         found = self.found(headers=headers)
     91         limit = self.limit or limit
     92         if found > limit:

/srv/conda/envs/notebook/lib/python3.7/site-packages/satsearch/search.py in found(self, headers)
     60         url = urljoin(self.url, 'search')
     61 
---> 62         results = self.query(url=url, headers=headers, **kwargs)
     63         # TODO - check for status_code
     64         logger.debug(f"Found: {json.dumps(results)}")

/srv/conda/envs/notebook/lib/python3.7/site-packages/satsearch/search.py in query(self, url, headers, **kwargs)
     78         # API error
     79         if response.status_code != 200:
---> 80             raise SatSearchError(response.text)
     81         return response.json()
     82 

SatSearchError: "Request failed with status code 400"
`

**Comment by scottyhq** [comment] 2021-02-23 20:59
> Will try and replicate this running cmr-stac locally to see if I can get to the bottom of it. 

@matthewhanson any updates on this? hopefully it will be fixed in the next update of https://cmr.earthdata.nasa.gov/stac ?

**Comment by matthewhanson** [comment] 2021-02-24 04:10
@scottyhq The fixes are in for this along with several other fixes and a change to the Collection names to be of the form <short_name>.v<version>.
They will get deployed to UAT (https://cmr.uat.earthdata.nasa.gov/stac) within the next couple days in case you would like to check it out, but it won't have the same data in it as production.

Production will be deployed with these fixes in 2 weeks, on March 9.

**Comment by scottyhq** [comment] 2021-03-10 17:40
> Production will be deployed with these fixes in 2 weeks, on March 9.

@matthewhanson I was eager to try this out to today, but still no luck. Here are some simplified query URLs showing what works and what doesn't for @kearney-sp 's HLSS30 collection that seems to be indexed in both UAT and Production:

Basically, it seems that the combination of specifying 'collection' in addition to other search parameters does not currently work in either UAT or production.

*UAT*:
```
https://cmr.uat.earthdata.nasa.gov/stac/LPCLOUDUAT/search?collections[]=HLSS30.v1.5
# 4202 matched, 10 returned

https://cmr.uat.earthdata.nasa.gov/stac/LPCLOUDUAT/search?datetime=2020-03-01/2020-04-01
# 1 returned (first item in collection from above search)

https://cmr.uat.earthdata.nasa.gov/stac/LPCLOUDUAT/search?collections[]=HLSS30.v1.5?datetime=2020-03-01/2020-04-01
# 0 returned
```

*production equivalent*
```
https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search?collections[]=C1711924822-LPCLOUD
# 733327 matched, 10 returned

https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search?datetime=2020-03-01/2020-04-01
# 1 returned (first item in collection from above search)

https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search?collections[]=C1711924822-LPCLOUD?datetime=2020-03-01/2020-04-01
# "Request failed with status code 400"
```

**Comment by matthewhanson** [comment] 2021-03-10 20:54
@scottyhq 
I've not been able to replicate this on production and it seems to work as expected.
Note that the production is using the new collection IDs, see # matched for each:

https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search
850491

https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search?collections[]=HLSS30.v1.5
734439

https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search?collections[]=HLSL30.v1.5
93184

https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search?datetime=2021-01-01/2021-02-01
146720

https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search?collections[]=HLSS30.v1.5&datetime=2021-01-01/2021-02-01
124157

https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search?collections[]=HLSL30.v1.5&datetime=2021-01-01/2021-02-01
22563

**Comment by scottyhq** [comment] 2021-03-11 01:19
Okay thanks for looking into it @matthewhanson! Maybe I jumped the gun before prod was actually changed! I also noticed I had '?' in place of '&' separators for the examples urls I manually put together in my comment above...

Returning to sat-search I think there are still some issues with the way certain query parameters are handled (`bbox` and `sortby`). Consider this comparison against the earthsearch endpoint:

```python
from satsearch import Search
results = Search(url='https://earth-search.aws.element84.com/v0',
                 collections=['sentinel-s2-l2a-cogs'], 
                 bbox = [-122.4,41.3,-122.1,41.5], 
                 datetime='2021-01-01/2021-02-01',
                 sortby='-properties.datetime',
                )
results.found()
```

```python
# constructs the following request:
# https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search?collections[]=HLSS30.v1.5&datetime=2021-01-01/2021-02-01&bbox=-122.4,41.3,-122.1,41.5

results = Search(url='https://cmr.earthdata.nasa.gov/stac/LPCLOUD',
                 collections=[collection], 
                 #bbox = [-122.4,41.3,-122.1,41.5], #SatSearchError: "Request failed with status code 400"
                 bbox = '-122.4,41.3,-122.1,41.5', #works! 
                 datetime='2021-01-01/2021-02-01',  
                 #sortby='-properties.datetime' # results in 0 found but no error raised
                )
results.found()
```

**Comment by matthewhanson** [comment] 2021-03-11 01:43
Thanks, I was thinking this was actually earth-search and sat-search that were wrong, but you are right, it's cmr-stac should be accepting an array:

https://github.com/radiantearth/stac-api-spec/blob/master/item-search/examples.md

In a GET request it should be a comma-delimited string, but that won't currently work with CMR-STAC until we fix the multiple parameters issue. 

Creating issue for this.

**Comment by matthewhanson** [comment] 2021-07-22 02:05
@scottyhq I think all these issues have been resolved, including all of the GET vs POST behavior.

pystac-client is now the preferred client library/CLI to use for STAC over sat-search

**Closed by matthewhanson** 2021-07-22 02:05 UTC
